:figure-caption: Figure 3-
:figure-num: 0

This section provides a list and description of the attributes that are governed by the CDB standard. Note that it is possible to provide attributes other than those listed here by making use of the Geomatics and Vendor Extended-level attribution schema.

[#table_cdb_attributes,reftext='{table-caption} {counter:table-num}']
.CDB attributes
[width="100%",cols="5%,10%,35%,50%",]
|===
|Code | Symbol | Attribute |

|1 |AEAC |*_Deprecated -_* ATARS Extended Attribute Code |

| | |Definition: |A unique numeric identifier that points to the entry
number of the ATARS Extended Attribution file for the current dataset.
This entry is provided for legacy database generation facility
considerations only; CDB-compliant devices are not required to read and
interpret this field. The ATARS Extended Attribution file should be
located in the same directory as the instance-level attribution file. An
empty AEAC field (i.e., null string) is allowed. Refer to Section 3.6.6,
Tiled Datasets Folder Hierarchical Organization for the file naming
conventions of vector datasets. NOTE: The AEAC is attribute is
deprecated as a result of the more comprehensive Extended-level
attribution schema introduced in version 3.1 of the CDB Specification.

| | |Level |Instance (Supported), Class (Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999999 ]

|2 |AHGT |Absolute Height Flag |

| | |Definition: |Specifies how to interpret vector geometry type
features with a Z component.

| | |Description: |If AHGT is true, the feature is positioned to the
value specified by the Z component (Absolute Terrain Altitude),
irrelevant of the terrain elevation dataset. If AHGT is false or not
present, the feature is positioned to the value specified by the
underlying terrain offset by the Z component value.

| | |UsageNote: |Optional. NOTE: It is recommended that the AHGT flag be
set to false because it facilitates the creation of CDB compliant
datasets that are independent of each other. Refer to section 10.7.1.1,
Vector Type Usage and Conventions for more details. Refer to Section 6.3
in Volume 7: CDB Data Model Guidance (formerly Appendix A) – “How to
Interpret the AHGT, HGT, BSR, BBH, and Z Attributes” for additional
usage guidelines. AHGT can be present only in datasets using PointZ,
PolylineZ, PolygonZ and MultiPointZ vector geometry types. AHGT should
not be present for all other vector geometry types or must be ignored
otherwise.NOTE: It is recommended that the AHGT flag be set to false
because it facilitates the creation of CDB compliant datasets that are
independent of each other. When the Z coordinate (altitude) of a feature
is relative to the ground, the terrain elevation dataset can be updated
without the need to recompute the altitude of the feature. CAUTION: When
the AHGT flag is set to true, the feature will be at a fixed WGS-84
elevation independently of the terrain LOD selected by the
client-device. As a result, there is no guarantee that the feature (and
its modeled representation) will remain above the terrain across all
terrain LODs. RECOMMENDATION: Limit the use of AHGT=TRUE to data whose
source is inherently absolute. Such source data include geodetic marks
or survey marks that provide a known position in terms of latitude,
longitude, and altitude. Good examples of such markers are boundary
markers between countries.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended (Not
Supported),

| | |Type |Boolean

| | |Format |Boolean

| | |Default |False

|3 |AO1 |Angle of Orientation with greater than 1 degree resolution |

| | |Definition: |The angular distance measured from true north (0 deg)
clockwise to the major Y-axis of the feature.

| | |Description: |If the feature is square, the axis 0 through 89.999
deg shall be recorded. If the feature is circular, 360.000 deg shall be
recorded.

| | |UsageNote: |Recommended. Applicable to point, Light point, Moving
Model Location and Figure point features. DEFAULT: CDB readers should
default to a value of 0.000 if AO1 is missing. When used in conjunction
with the PowerLineNetwork dataset, AO1 corresponds to the orientation of
the Y-axis of the modeled pylon. The modeled pylon should be oriented
(in its local Cartesian space) so that the wires nominally attach along
the Y-axis. Refer to Section 6.1 Volume 7: CDB Data Model Guidance
(formerly Appendix A) – “Creating a 3D Model for a Powerline Pylon” for
additional usage guidelines.

| | |Compatibility: |OGC CDB 1.0, DIGEST v2.1

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |3.3

| | |Range |[ 0 , 360 )

| | |Default |0

| | |Unit |2

|4 |APFN |*_Deprecated -_* Airport Feature Name |

| | |Definition: |...

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Text

| | |Length |24

|5 |APID |AirPort ID |

| | |Definition: |A unique alphanumeric identifier that points to a
record in the NavData Airport or Heliport dataset (i.e., a link to the
Airport or the Heliport description in the NavData dataset).

| | |Description: |This ID is the value of the field Ident of the
Airport or Heliport dataset.

| | |UsageNote: |Optional for Points, Location Points, Environmental
Light Points, and Moving Model Location features that fall within the
confines of an airport and for which control of the feature is
desirable. Recommended for all Airport Light Points and airport-related
T2DModels (such as runway/taxiway/apron surfaces, and markings). Note
that all of the lights located in vector datasets that are associated
with the operation of an airport (including runway lights and lighting
systems) are required to reference an airport or heliport in the NavData
dataset. All man-made features associated with an airport or heliport
must be assigned an APID attribute; the APID attribute is not required
for features unrelated to airports or heliports. Failure to
appropriately tag airport culture with APID attribute will result in
reduced control of airport-related culture by simulator.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |6

| | |Default |None

|6 |BBH |Bounding Box Height |

| | |Definition: |The Height of the Bounding Box of the 3D model
associated with a point feature.

| | |Description: |It is the dimensions of the box centered at the model
origin and that bound the envelopes of all articulated parts. BBH refers
to height of the box above the XY plane of the model. Note that for 3D
models used as cultural features, the XY plane of the model corresponds
to its ground reference plane. The value of BBH, BBW and BBL should be
accounted for by client-devices (in combination with other information)
to determine the appropriate distance at which the model should be
paged-in, rendered or processed. BBH, BBW and BBL are usually generated
through database authoring tool automation.

| | |UsageNote: |Optional on features for which a MODL has been
assigned. DEFAULT: When missing, CDB readers should default BBH to the
value of BSR, and BBW and BBL to twice the value of BSR. The Default tag
is set to 0.000 to be machine readable per disscussed in this issue
(https://github.com/opengeospatial/cdb-schema/issues/14) in the CDB SWG
meeting. The dimension of the bounding box is intrinsic to the model and
identical for all LOD representations. Refer to Section 6.3 of the OGC
CDB 1.2 - Volume 7: CDB Data Model Guidance (formerly Appendix A) – “How
to Interpret the AHGT, HGT, BSR, BBH, and Z Attributes” for additional
usage guidelines.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |( 0 , 99999.999 )

| | |Default |0.000

| | |Unit |1

|7 |BBW |Bounding Box Width |

| | |Definition: |The Width of the Bounding Box of the 3D model
associated with a point feature.

| | |Description: |It is the dimensions of the box centered at the model
origin and that bound the envelopes of all articulated parts. BBW refers
to the width of the box along the X-axis. Note that for 3D models used
as cultural features, the XY plane of the model corresponds to its
ground reference plane. The value of BBH, BBW and BBL should be
accounted for by client-devices (in combination with other information)
to determine the appropriate distance at which the model should be
paged-in, rendered or processed. BBH, BBW and BBL are usually generated
through database authoring tool automation. See BBH for a complete
description.

| | |UsageNote: |Optional on features for which a MODL has been
assigned. DEFAULT: When missing, CDB readers should default BBH to the
value of BSR, and BBW and BBL to twice the value of BSR. The Default tag
is set to 0.000 to be machine readable per disscussed in this issue
(https://github.com/opengeospatial/cdb-schema/issues/14) in the CDB SWG
meeting. The dimension of the bounding box is intrinsic to the model and
identical for all LOD representations. Refer to Section 6.3 of the OGC
CDB 1.2 - Volume 7: CDB Data Model Guidance (formerly Appendix A) – “How
to Interpret the AHGT, HGT, BSR, BBH, and Z Attributes” for additional
usage guidelines.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |( 0 , 99999.999 )

| | |Default |0.000

| | |Unit |1

|8 |BBL |Bounding Box Length |

| | |Definition: |The Length of the Bounding Box of the 3D model
associated with a point feature.

| | |Description: |It is the dimensions of the box centered at the model
origin and that bound the envelopes of all articulated parts. BBL refers
to the length of the box along the Y-axis. Note that for 3D models used
as cultural features, the XY plane of the model corresponds to its
ground reference plane. The value of BBH, BBW and BBL should be
accounted for by client-devices (in combination with other information)
to determine the appropriate distance at which the model should be
paged-in, rendered or processed. BBH, BBW and BBL are usually generated
through database authoring tool automation.

| | |UsageNote: |Optional on features for which a MODL has been
assigned. DEFAULT: When missing, CDB readers should default BBH to the
value of BSR, and BBW and BBL to twice the value of BSR.The Default tag
is set to 0.000 to be machine readable per disscussed in this issue
(https://github.com/opengeospatial/cdb-schema/issues/14) in the CDB SWG
meeting. The dimension of the bounding box is intrinsic to the model and
identical for all LOD representations. Refer to Section 6.3 of the OGC
CDB 1.2 - Volume 7: CDB Data Model Guidance (formerly Appendix A) – “How
to Interpret the AHGT, HGT, BSR, BBH, and Z Attributes” for additional
usage guidelines.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |( 0 , 99999.999 )

| | |Default |0.000

| | |Unit |1

|9 |BOTY |Boundary Type |

| | |Definition: |A value that uniquely attributes a boundary according
to the enumerators found here.

| | |UsageNote: |Optional. See Table 5-19 of the OGC CDB 1.2 - Volume 1
which is captured in the enumeration tag for a list of accepted values.
Can be used only with Boundary point, line or polygon Feature Datasets
(which are part of the Geopolitical Datasets)

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !Continental
!2 !International
!3 !Interstate
!4 !Inter-provincial
!5 !Territorial
!6 !Economic
!7 !Regional
!8 !Communal
!9 !Tourist
!10 !Private Zone
!11 !Military District
!12 !Disputed
!13 !Populated Place
!14 !Non-capital City
!15 !Time Zone Delimiter
!16 !International Date Line
!17 !Capital City
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Default |0

|10 |BSR |Bounding Sphere Radius |

| | |Definition: |The radius of a feature.

| | |Description: |In the case where a feature references an associated
3D model, it is the radius of the hemisphere centered at the model
origin and that bounds the portion of the model above its XY plane,
including the envelopes of all articulated parts. Note that for 3D
models used as cultural features, the XY plane of the model corresponds
to its ground reference plane. The value of BSR should be accounted for
by client-devices (in combination with other information) to determine
the appropriate distance at which the model should be paged-in, rendered
or processed. When the feature does not reference a 3D model, BSR is the
radius of the abstract point representing the feature (e.g., a city).

| | |UsageNote: |Mandatory for features for which a MODL has been
assigned, but optional for geopolitical point features. The dimension of
the bounding sphere is intrinsic to the model and identical for all LOD
representations. Refer to Section 6.3 of the OGC CDB 1.2 - Volume 7: CDB
Data Model Guidance (formerly Appendix A) – “How to Interpret the AHGT,
HGT, BSR, BBH, and Z Attributes” for additional usage guidelines. The
Default tag is set to 0.000 to be machine readable per disscussed in
this issue (https://github.com/opengeospatial/cdb-schema/issues/14) in
the CDB SWG meeting.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |( 0 , 99999.999 )

| | |Length |9

| | |Default |0.000

| | |Unit |1

|11 |CEAI |CDB Extended Attribute Index |

| | |Definition: |An index that points to a row entry of a CDB Extended
Attribution file for the current dataset.

| | |Description: |This entry permits users to store an index to a link
list set of CDB-specific attributes. CDB-compliant devices must be
capable of reading and interpreting this field. Usage of this
attribution is not portable to other simulators because it falls outside
of the documented CDB attribution scheme. An empty CEAI attribute is
allowed.

| | |UsageNote: |Optional. Use when CDB extended attribution is
required. A value of 0 indicates that there are no CDB Extended
attributes. NOTE: The first entry in the CDB Extended Attribution file
has an index of 1. The CDB Extended Attribution file should be located
in the same directory as the instance-level attribution file.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended (Not
Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

| | |Length |6

| | |Default |0

|12 |CEAC |*_Deprecated -_* CDB Extended Attribute Code |

| | |Definition: |A unique numeric identifier that points to the entry
number of a CDB Extended Attribution file for the current dataset. This
entry permits users to store a link to a set of CDB-specific attributes
beyond those explicitly supported by the current version of this
Specification. CDB-compliant devices may optionally read and interpret
this field due to program requirements that cannot be supported by the
current version of the CDB. Usage of this attribution is not portable to
other simulators because it falls outside of the documented CDB
attribution scheme. The CDB Extended Attribution file should be located
in the same directory as the instance-level attribution file. An empty
CEAC field is allowed. Refer to Section 3.6.6, Tiled Datasets Folder
Hierarchical Organization for the file naming conventions of vector
datasets. NOTE: The CEAC attribute is deprecated as a result of the more
comprehensive Extended-level attribution schema introduced in version
3.1 of the CDB Specification.

| | |Level |Instance (Deprecated), Class (Deprecated),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999999 ]

|13 |CMIX |Composite Material Index |

| | |Definition: |Index into the Composite Material Table Section
7.5.2.2 (?) of the OGC CDB 1.2 - Volume 1 is used to determine the Base
Materials composition of the associated feature.

| | |Description: |Refer to Section 2.5, Material Naming Conventions for
a description on material naming conventions.

| | |UsageNote: |Mandatory for all vector datasets that represent
features except for GeoPolitical vector datasets.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

| | |Length |6

| | |Default |None

|14 |CNAM |Class Name |

| | |Definition: |A name that represents the Attribution Class.

| | |Description: |The class-level attribution schema is described in
Section 10.7.1.2.7.2, Class-level Schema. Attributes are referenced via
this classname. The classname is used as the primary key to perform
searches within the Dataset Class Attribute file.

| | |UsageNote: |Each row of a class-level database file (e.g., *.dbf)
or table must have a valid CNAM entry; the CNAM must be unique within
the file. Each row of an instance-level database file (e.g., *.dbf) can
optionally use the CNAM to refer to class attributes; blank indicates
“no class attribute”.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Supported), Class (Supported), Extended (Not
Supported),

| | |Type |Text

| | |Length |32

| | |Default |None

|15 |DEAC |*_Deprecated -_* DIGEST Extended Attribute Code |

| | |Definition: |A unique numeric identifier that points to the entry
number of the DIGEST Extended Attribution file for the current dataset.
This entry is provided for legacy database generation facility
considerations only; it provides a means for the CDB to act as a
repository for legacy DIGEST attribution. CDB-compliant devices are not
required to read and interpret this field. The DIGEST Extended
Attribution file should be located in the same directory as the
instance-level attribution file. An empty DEAC field (i.e., null string)
is allowed. Refer to Section 3.6.6, Tiled Datasets Folder Hierarchical
OrganizationDirectory for the file naming conventions of vector
datasets. Optional. Use when DIGEST extended attribution is required.
NOTE: The DEAC attribute is deprecated as a result of the more
comprehensive Extended-level attribution schema introduced in version
3.1 of the CDB Specification.

| | |Level |Instance (Deprecated), Class (Deprecated),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999999 ]

|16 |DEP |Depth below Surface Level |

| | |Definition: |Distance measured from the highest point at surface
level to the lowest point of the feature below the surface (The depth of
a feature).

| | |Description: |DEP values are positive numbers. If the feature has
no modeled representation, its depth is measured as the distance from
the surface level to the lowest point of the feature below the surface
(Surface here refers to the terrain in the immediate vicinity of the
feature). If the feature has an associated 3D model, the depth is
measured as the distance from the XY plane of the model to the lowest
point of the model below that plane. In the case of ground features, DEP
refers to the portion of the feature (or its modeled representation)
that is underground. In the case of moving models that are used as
geotypical features, DEP refers to the portion of the model that is
below the waterline (i.e., the XY plane). In the case of network line
features such as roads, railroads and powerlines, DEP refers to the
depth of the feature under the ground in its vicinity. In the case of
hydrographic features, DEP refers to the depth of rivers, lakes, etc
(Note, that the CDB has provision for a raster dataset to represent the
bathymetry. When provided, the dataset provides a much more detailed
underwater profile of hydrographic features).

| | |UsageNote: |Applicable to line features with depth, especially for
HydrographyNetwork Dataset features. Not applicable to features that are
intrinsically above ground. This data is typically used by
client-devices that need to determine whether or not a waterway is
navigable by ships with a specific draw.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |( 0.000 , 99999.999 )

| | |Length |9

| | |Default |0.000

| | |Unit |1

|17 |DIR |Directivity |

| | |Definition: |The side or sides of a feature that has the greatest
reflectivity potential.

| | |Description: |This data is typically needed for Radar simulation.
DIR is used solely for line features in accordance to DFAD conventions.
If DIR is not equal to 3, then AO1 is the angular distance measured from
true north (0 deg) clockwise to the reflective side of the feature.

| | |UsageNote: |Recommended for line features. If absent,
client-devices are required to default to a value of 3 –
Omni-directional. Enumerated per DIGEST: value of 1 means
Uni-directional, value of 2 means Bi-directional, value of 3 means
Omni-directional.

| | |Compatibility: |OGC CDB 1.0, DIGEST

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |3

|18 |DML |Density Measure (% light cover) |

| | |Definition: |Percentage of light coverage at night within the area
delimited by a polygon feature.

| | |Description: |Percentage of light coverage at night (expressed as a
percentage) within the area delimited by a polygon feature.

| | |UsageNote: |Recommended. Applies to Geopolitical Dataset polygon
features that delineate inhabited areas. DEFAULT:If this field is
absent, client-devices shall assume 0%.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 100 ]

| | |Length |3

| | |Default |0

| | |Unit |7

|19 |DMR |Density Measure (% roof cover) |

| | |Definition: |Percentage of roof coverage within the area delimited
by a polygon feature.

| | |Description: |Roof cover measure by percent within area of feature.

| | |UsageNote: |Recommended for polygon features. DEFAULT:If absent,
client-devices shall assume 0%.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 100 ]

| | |Length |3

| | |Default |0

| | |Unit |7

|20 |DMS |Density Measure (structure count) |

| | |Definition: |Number of man-made structures per square kilometer of
polygon features.

| | |Description: |Canopy cover measure by percent within area of
feature during the summer season.

| | |UsageNote: |Recommended for polygon features. DEFAULT: If absent,
client-devices shall assume 0. NOTE: Range values differ from DIGEST
range of -32767 to 32768

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 99999 ]

| | |Length |5

| | |Default |0

|21 |DMT |Density Measure (% tree/canopy cover) |

| | |Definition: |Percentage of canopy coverage within the area
delimited by a polygon feature during the summer season.

| | |Description: |Canopy/tree cover measure by percent within area of
feature during the summer season.

| | |UsageNote: |Recommended for polygon features. DEFAULT:If absent,
client-devices shall assume 0%.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 100 ]

| | |Length |3

| | |Default |0

| | |Unit |7

|22 |EJID |End Junction ID |

| | |Definition: |A unique Junction Identification Number that is used
to virtually connect the end point of a line feature to another point,
line or polygon feature.

| | |Description: |line features stored in the same vector file having
the same SJID or EJID are connected. line features stored in different
vector files having the same SJID or EJID as the JID listed in the
corresponding tile 2D relationship file are connected.

| | |UsageNote: |Mandatory for all features belonging to Topological
Network Datasets. FORMAT: Unsigned integer64 as character string.
Attribute is stored as a character string representing an unsigned
64-bit number and requires conversion back into numerical representation
by client reader. This is due to the 32-bit limitation on integer values
within dBASE files (e.g., *.dbf). NOTE: In the OGC CDB 1.2 - Volume 1,
"Data Type" is text numerals and "Format" is unsigned integer64 as
character string which is different from this xml (Type: Numeric and
Format: Integer). RANGE: 0 to (2^64 – 1) according to the OGC CDB 1.2 -
Volume 1.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Length |20

| | |Default |0

|23 |FACC |Feature Attribute Classification Code |

| | |Definition: |Feature and Attribute Coding Catalogue (FACC) Data
Dictionary provides a common menu of features and attributes along with
a standardized coding system by DIGEST.

| | |Description: |This code used to distinguish and categorize features
within a dataset.

| | |UsageNote: |Mandatory. The enumerated codes are listed in
/CDB/Metadata/Feature_Data_Dictionary.xml. FORMAT: Two alpha characters
following by three digits.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |5

| | |Default |None

|24 |FSC |Feature Sub Code |

| | |Definition: |The CDB standard defines an additional attribute
called feature sub-code (FSC) to define a broader set of feature types.

| | |Description: |This code, in conjunction with the feature code is
used to distinguish and categorize features within a dataset.

| | |UsageNote: |Mandatory. The enumerated codes are in accordance to
/CDB/Metadata/Feature_Data_Dictionary.xml.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |None

|25 |GAID |Gate AirPort ID |

| | |Definition: |A unique alphanumeric identifier (for the airport in
question) that is consistent with the IDENT attribute name within the
NavData Gate dataset.

| | |Description: |This ID is the value of the Gate Identifier of the
Gate dataset and can be used to extract additional information such as
the gate position and bearing.

| | |UsageNote: |Recommended and Optional usages are per Table 5-27 of
the OGC CDB 1.2 - Volume 1: Allocation of CDB Attributes to Vector
Datasets. Typically used (but not limited to) for models such as docking
systems, marshallers and other models that are logically associated with
a Terminal gate and that require some level of control by the simulation
application.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |6

| | |Default |None

|26 |GEAI |Geomatics Extended Attribute Index |

| | |Definition: |An index that points to a row entry of a Geomatics
Extended Attribution file for the current dataset.

| | |Description: |This entry permits users to store an index to a link
list set of Geomatics-specific attributes. CDB-compliant devices are not
mandated to read and interpret this field. Usage of this attribution is
not portable to other simulators because it falls outside of the
documented CDB attribution scheme. The Geomatics Extended Attribution
file should be located in the same directory as the instance-level
attribution file. An empty GEAI attribute is allowed. Note that the
first entry in the Geomatics Extended Attribution file has an index of
1.

| | |UsageNote: |Optional. Use when Geomatics extended attribution is
required. A value of 0 indicates that there are no Geomatics Extended
attributes.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended (Not
Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

| | |Length |6

| | |Default |0

|27 |HGT |Height above surface level |

| | |Definition: |The height of a feature. Distance measured from the
lowest point of the base at ground (non-floating objects) or water level
(floating objects downhill side/downstream side) to the tallest point of
the feature above the surface.

| | |Description: |HGT values are positive numbers. If the feature has
no modeled representation, its height is measured as the distance from
the surface level (ground or water) to the tallest point of the feature
above the surface (Surface here refers to the terrain in the immediate
vicinity of the feature). If the feature has an associated 3D model, the
height is measured as the distance from the XY plane of the model to the
highest point of the model above that plane. In the case of ground
features, HGT refers to the portion of the feature (or its modeled
representation) that is meant to be above ground. In the case of network
line and polygon features such as roads, railroads, powerlines, or
forest, HGT refers to the elevation of the feature relative to the
terrain in its immediate vicinity.

| | |UsageNote: |Mandatory on all point and Figure point features for
which a MODL has been assigned. Recommended on line features except
coastline (coastlines are assumed to be zero). Recommended on all
polygons features. Optional for Airport and Environmental Light Points.
Refer to Section 6.1 Volume 7: CDB Data Model Guidance (formerly
Appendix A) – "How to Interpret the AHGT, HGT, BSR, BBH, and Z
Attributes" for additional usage guidelines. DEFAULT: Value must be
provided for point and Figure point features. For the line and polygon
features, a default value of 0.00 should be used.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |4.2

| | |Range |[ 0.00 , 9999.99 ]

| | |Length |7

| | |Default |0.00

| | |Unit |1

|28 |JID |Junction ID |

| | |Definition: |A unique Junction Identification Number that is used
to virtually connect a point or a polygon feature to another point, line
or polygon feature.

| | |Description: |Features stored in the same vector file having the
same JID are connected. Features stored in different vector files having
the same JID as the JID listed in the corresponding tile 2D relationship
file are connected. When JID is associated to a polygon feature, it
necessarily connects to the first point of the polygon feature.

| | |UsageNote: |Mandatory for all features belonging to Topological
Network Datasets. Attribute is used in 2D relationship file. Attribute
is stored as a character string representing an unsigned 64-bit number
and requires conversion back into numerical representation by client
reader. This is due to the 32-bit limitation on integer values within
dBASE files (e.g., *.dbf). NOTE: In the OGC CDB 1.2 - Volume 1, "Data
Type" is text numerals and "Format" is unsigned integer64 as character
string which is different from this xml. RANGE: 0 to (2^64 – 1)
according to the OGC CDB 1.2 - Volume 1.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Length |20

| | |Default |None

|29 |LACC |Location Accuracy |

| | |Definition: |A precision value used to quantify the relative
precision of the Location point representing the specific GeoPolitical
Location.

| | |UsageNote: |Optional. See Table 5-20 of the OGC CDB 1.2 - Volume 1:
Location Accuracy Enumeration Values for a list of accepted values which
is captured in the enumeration tag.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !Better or equal to 10 m.
!2 !Better or equal to 100 m.
!3 !Better or equal to 250 m.
!4 !Better or equal to 500 m.
!5 !Better or equal to 1200 m.
!6 !Greater than 1200 m.
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|30 |LENL |Length of Lineal |

| | |Definition: |The length of a line feature.

| | |Description: |If the feature has been clipped to a tile boundary,
the length still gives the initial full length of the object prior to
the clipping operation, and if it belonged to a topological network,
LENL will represent the distance between the two closest junction points
encompassing this line segment. Note the Length attribute is not used to
define a bounding sphere associated to an object, but rather to provide
a weight to the relative length of the lineal (line feature) as compared
to others.

| | |UsageNote: |Mandatory for all networked line features. Length
computation should be account for the earth’s curvature.

| | |Compatibility: |OGC CDB 1.0, SEDRIS (EA = 562)

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

| | |Length |6

| | |Default |None

| | |Unit |1

|31 |LMIX |*_Deprecated -_* Light Material Index |

| | |Definition: |Index into the Composite Material Table that is used
to determine the Light Material composition of the associated city
illumination. Represent the predominant material characterizing the
major light attributes of a populated area. Refer to Section 2.5,
Material Naming Conventions for a description on material naming
conventions. Optional. Applicable to Geopolitical Dataset polygon
features that delineate inhabited areas. NOTE: The LMIX attribute is
deprecated in version 3.1 of the CDB specification.

| | |Level |Class (Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|32 |LNAM |Feature (or Location) Name |

| | |Definition: |A name that corresponds to a GeoPolitical Location.

| | |Description: |A toponym – a general term for any place or
geographical entity. The attribute is used to give a proper noun (a
human readable name) to any feature from any vector dataset.

| | |UsageNote: |Optional. Blank indicates "no name". The use of LNAM
goes from the name of a City to the name of a Road, to the name of a
Building, etc. Multiple names are possible when using LNAM as an
extended attribute. When more than one name is provided, they must
appear in order from the shortest name to the longest one.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Text

| | |Length |32

| | |Default |Blank

|33 |LOTY |Location Type |

| | |Definition: |A value that uniquely attributes the location type of
point, line or polygon features.

| | |Description: |A value that uniquely attributes a location feature
according to the enumerators found here.

| | |UsageNote: |Optional. Applicable to Geopolitical Dataset polygon
features. Enumeration per Table 5-21 of the OGC CDB 1.2 - Volume 1:
Location Type Enumeration Values. Can be used only with Location point,
line or polygon Feature Datasets (which are part of the Geopolitical
Datasets). NOTE: In cases where the location represents a bounded area,
the approximate geometric center is assumed.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !Continent
!2 !Country
!3 !State
!4 !Capital
!5 !Province
!6 !City
!7 !Municipality
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|34 |LPH |Light Phase |

| | |Definition: |A value that controls the phase of the light.

| | |Description: |Used for all light types that are periodic in nature
(rotating, blink, flashing, etc). The value of LPH controls the phase of
the light relative to all other lights that share the same LTYP. All
other light characteristics, including frequency and duration are
implicitly determined by the LTYP.

| | |UsageNote: |Optional. DEFAULT: In absence of a value, LPH defaults
to a value of 0. Unit: Thousands of a cycle.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|35 |LPN |Layer Priority Number |

| | |Definition: |A priority number that establishes the relative
priority of overlapping features.

| | |Description: |LPN establishes the order (starting from 0 for lowest
priority) by which overlapping features are processed by client-devices.

| | |UsageNote: |Mandatory for terrain constraint features that overlap
one another. For all other features, LPN is optional. LPN is derived
from priority information stored and maintained by the authoring tools.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 32767 ]

| | |Length |5

| | |Default |None

|36 |LTN |Lane/Track Number |

| | |Definition: |The number of lanes on a road, tracks on railroad, or
conductors on powerlines, including both directions.

| | |Description: |The number of lanes on a road, tracks on railroad, or
conductors on powerlines, including both directions.

| | |UsageNote: |Recommended for Road, RailRoad, and PowerLineNetwork
features. Optional for Hydrography Network features. NOTE: The range
value is between 0 to 99 which differs from DIGEST range of -32767 to
32768. DEFAULT: 01 – for encoding RailRoadNetwork line features, 02 –
for encoding RoadNetwork or PowerLineNetwork line features.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 99 ]

| | |Length |2

| | |Default |01 – for RailRoadNetwork line features; 02 – for
RoadNetwork or PowerLineNetwork line features.

|37 |LTYP |Light Type |

| | |Definition: |A unique code corresponding to a Light Type.

| | |Description: |The light types follow a hierarchical organization
provided by the light type naming conventions described in Section 7.3
of the OGC CDB 1.2 - Volume 1, Light Naming. Lights schema definition
(/CDB/Metadata/Lights.xsd file) of the OGC CDB 1.2 (Formerly Volume 2
Annex J) provides the supported light types. The Lights.xml file
(located in CDB\Metadata directory of the CDB storage structure)
establishes the correspondence between the LTYP code and the Light Type
name.

| | |UsageNote: |Mandatory for all Airport Light point features,
Environmental Light point features.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 9999 ]

| | |Length |4

| | |Default |0

|38 |MLOD |Model Level Of Detail |

| | |Definition: |The level of detail of the 3D model associated with
the point feature.

| | |Description: |The level of detail of the 3D model associated with
the point feature.

| | |UsageNote: |When used in conjunction with MODL, the MLOD attribute
indicates the LOD where the corresponding MODL is found. In this case,
the value of MLOD can never be larger than the LOD of the Vector
Tile-LOD that contains it. When used in the context of Airport and
Environmental Light point features, the value of MLOD, if present,
indicates that this Light point also exist in a 3D model found at the
specified LOD. In such case, the value of MLOD is not constrained and
can indicate any LOD.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ -10 , 23 ]

| | |Length |3

| | |Default |None

|39 |MMDC |Moving Model DIS Code |

| | |Definition: |A character string composed of the 7 fields of the DIS
Entity Type.

| | |Description: |A character string composed of the 7 fields of the
DIS Entity Type which is separated by an underscore character (“_”) and
formatted like this: 1_2_3_4_5_6_7.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |29

| | |Default |None

|40 |MODL |Model Name |

| | |Definition: |A string referring to the model name.

| | |Description: |A string reference, the model name, which stands for
the modeled geometry of a feature; in the case of buildings, this
includes both its external shell and modeled interior.

| | |UsageNote: |Recommended for point features, Road Figure point
features, Railroad Figure point features, Pipeline Figure point features
and Hydrography Figure point features that are modeled using some
industry format. MODL can also be used with Road line features, Railroad
line features, Pipeline line features and Hydrography line and polygon
features. NOTE: It is not permitted to specify a value for MODL
simultaneously with a value for MMDC. FORMAT: Per conventions described
in section 8 from the OGC CDB 1.2 - Volume 1, CDB Structure.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |32

| | |Default |None

|41 |MODT |Model Type |

| | |Definition: |A flag indicating whether the modeled feature is
geo-typical, geo-specific or a moving model.

| | |Description: |MODT indicates whether a feature is represented using
a geotypical, geospecific or moving model. Together, the MODT,
FeatureCode, FSC, and MODL model name or the MMDC produce a unique path
to a directory within the CDB hierarchy and a unique filename within
that directory identifies a unique model into the CDB.

| | |UsageNote: |Needed for features that are modeled using a CDB
specified format. "T" for geo-typical, "S" for geo-specific, "M" for
Moving Model. DEFAULT: "S" when not present.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |1

| | |Default |"S"

|42 |NCS1 |Network Component Selector 1 |

| | |Definition: |This attribute is used to identify component selector
1 of Network datasets.

| | |Description: |Code that is used to identify the component selector
1 file which contain the point, line, or polygon feature that is
virtually connected.

| | |UsageNote: |Mandatory for Network datasets. Attribute is used in 2D
relationship file. FORMAT: Unsigned integer.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 9999 ]

| | |Length |4

| | |Default |None

|43 |NCS2 |Network Component Selector 2 |

| | |Definition: |This attribute is used to identify component selector
2 of Network datasets.

| | |Description: |Code that is used to identify the component selector
2 file which contain the point, line, or polygon feature that is
virtually connected.

| | |UsageNote: |Mandatory for Network datasets. Attribute is used in 2D
relationship file.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 9999 ]

| | |Length |4

| | |Default |None

|44 |NDSC |Network Dataset Code |

| | |Definition: |This attribute is used to identify the Network dataset
code.

| | |Description: |Code that is used to identify the dataset code file
which contain the point, line, or polygon feature that is virtually
connected.

| | |UsageNote: |Mandatory for Network datasets. Attribute is used in 2D
relationship file. FORMAT: Unsigned integer.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 9999 ]

| | |Length |4

| | |Default |None

|45 |NIS |*_Deprecated -_* Number of Instances |

| | |Definition: |Number of instances found in the 3D model associated
with the cultural point feature.

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|46 |NIX |*_Deprecated -_* Number of Indices |

| | |Definition: |Number of indices found in the 3D model associated
with the cultural point feature.

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|47 |NNL |*_Deprecated -_* Number of Normals |

| | |Definition: |Number of normal vectors found in the 3D model
associated with the cultural point feature.

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|48 |NTC |*_Deprecated -_* Number of Texture Coordinates |

| | |Definition: |Number of texture coordinates found in the 3D model
associated with the cultural point feature.

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|49 |NTX |*_Deprecated -_* Number of Texels |

| | |Definition: |Number of texels found in the 3D model associated with
the cultural point feature.

| | |Level |Class (Deprecated), Extended (Preferred),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999999 ]

|50 |NVT |*_Deprecated -_* Number of Vertices |

| | |Definition: |Number of vertices of the 3D model associated with a
point feature.

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

|51 |POPD |Population Density |

| | |Definition: |The number of inhabitants per square kilometer.

| | |Description: |The number of inhabitants per square kilometer.

| | |UsageNote: |Applicable to Geopolitical features representing
inhabited areas. UNIT: Inhabitants per square kilometer.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 99999 ]

| | |Length |5

| | |Default |0

|52 |POPT |Populated Place Type |

| | |Definition: |A value that uniquely represents the Populated Place
Attribution Type.

| | |Description: |This attribute should be used in conjunction with the
BOTY attribute when BOTY has an (enumerator) value of 13 which
corresponds to "Populated Place".

| | |UsageNote: |Optional. Applies to Geopolitical Dataset polygon
features that delineate inhabited areas. Enumeration per Table 5-22 from
the OGC CDB 1.2 - Volume 1: Populated Place Type Enumeration Values.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !Native Settlement
!2 !Shanty Town
!3 !Tent Dwellings
!4 !Inland Village
!5 !Small City (less than 20,000 inhabitants)
!6 !Medium City (between 20,000 and 500,000 inhabitants)
!7 !Large City (more than 500,000 inhabitants)
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|53 |RTAI |Relative Tactical Importance |

| | |Definition: |Provides the Relative TActical Importance of moving
models or cultural features relative to other features for the purpose
of client-device scene/load management.

| | |Description: |A value of 100% corresponds to the highest
importance; a value of 0% corresponds to the lowest importance. When
confronted with otherwise identical objects that differ only wrt to
their Relative TActical Importance, client-devices should always discard
features with lower importance before those of higher importance in the
course of performing their scene / load management function. As a
result, a value of zero gives complete freedom to client-devices to
discard the feature as soon as the load of the client-device is
exceeded. The effectiveness of scene / load management functions can be
severely hampered if large quantities of features are assigned the same
Relative TActical Importance by the modeler. In effect, if all models
are assigned the same value, the client-devices have no means to
distinguish tactically important objects from each other. Assigning a
value of 1% to all objects is equivalent to assigning them all a value
of 99%. Ideally, the assignment of tactical importance to features
should be in accordance to a histogram similar to the one shown here.
The shape of the curve is not critical, however the proportion of models
tagged with a high importance compared to those with low importance is
critical in achieving effective scene/load management schemes. It is
illustrated here to show that few models should have an importance of
100 with progressively more models with lower importance. The assignment
of the RTAI to each feature lends itself to database tools automation.
For instance, RTAI could be based on a look-up function which factors
the feature’s type (FeatureCode or MMDC). RTAI=f(FeatureCode_or_MMDC)
The value of Relative TActical Importance should be accounted for by
client-devices (in combination with other information) to determine the
appropriate distance at which the feature (and its modeled
representation, if available) should be rendered or processed. Relative
TActical Importance is mandatory. It has no default value. For more
details on RTAI Typical Usage Histogram, please refer to Figure 5-31 of
the OGC CDB 1.2 - Volume 1.

| | |UsageNote: |Mandatory. All features should be tagged with an
appropriate value for the reasons stated in Description tag of this xml
file or section 10.7.1.3.53 of the OGC CDB 1.2 - Volume 1. NOTE: The
importance of the model can be further modified at run-time at the
simulator console through the scenario importance value assigned to the
model.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended (Not
Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 100 ]

| | |Length |3

| | |Default |None

| | |Unit |7

|54 |RWID |Runway ID |

| | |Definition: |This ID is the value of the field Ident of the Runway
or Helipad dataset.

| | |Description: |An alphanumeric identifier that, combined with the
APID, points to a unique record in the NavData Runway or Helipad dataset
(i.e., a link to the Runway or Helipad description in the NavData
dataset).

| | |UsageNote: |Recommended for all Airport Light Points features.
Optional for point/line/polygon features, Location Points Features,
Environmental Light point features, and Moving Model Location features
that are associated with a runway and for which control of the feature
is desirable. Failure to appropriately tag airport culture with RWID
attribute will result in reduced control of runway-related (or helipad)
culture by simulator. The combination of RWID and APID points to a
unique record of the NavData Runway or Helipad dataset components. Note
that all of the lights and other features located in vector datasets
that are associated with the operation of a runway or helipad are
required to reference a runway or helipad in the NavData dataset; the
RWID attribute is not required for features unrelated to a runway or
helipad.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |6

| | |Default |None

|55 |SCALx |Scaling X-Axis |

| | |Definition: |A scaling factor for the model X-axis, to be applied
to the rendering of model geometry by the client device.

| | |Description: |A set of scaling factors, one of the model axis, to
be applied to the rendering of model geometry by the client-device.

| | |UsageNote: |Optional. DEFAULT: A value of 1.0 if SCALx, SCALy, or
SCALz is missing. A value of 1.0 instructs the client-devices to use the
model as-is. The physical dimension of models processed by client-device
should approach zero, as SCALing tends to zero. The value of SCALing
should also be accounted for by client-devices (in combination with
other information) to determine the appropriate distance at which the
model should be paged-in, rendered or processed. All three SCALing
factors are optional. Values of zero and negative values are not
permitted.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |3.5

| | |Range |[ 000.00001 , 999.99999 ]

| | |Length |9

| | |Default |1.0

|56 |SCALy |Scaling Y-Axis |

| | |Definition: |A scaling factor for the model Y-axis, to be applied
to the rendering of model geometry by the client device.

| | |Description: |Scale factor to apply to the Y-axis of the model.

| | |UsageNote: |Optional. DEFAULT: A value of 1.0 if SCALx, SCALy, or
SCALz is missing. A value of 1.0 instructs the client-devices to use the
model as-is. The physical dimension of models processed by client-device
should approach zero, as SCALing tends to zero. The value of SCALing
should also be accounted for by client-devices (in combination with
other information) to determine the appropriate distance at which the
model should be paged-in, rendered or processed. All three SCALing
factors are optional. Values of zero and negative values are not
permitted.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |3.5

| | |Range |[ 000.00001 , 999.99999 ]

| | |Length |9

| | |Default |1.0

|57 |SCALz |Scaling Z-Axis |

| | |Definition: |A scaling factor for the model Z-axis, to be applied
to the rendering of model geometry by the client device.

| | |Description: |Scale factor to apply to the Z-axis of the model.

| | |UsageNote: |Optional. DEFAULT: a value of 1.0 if SCALx, SCALy, or
SCALz is missing. A value of 1.0 instructs the client-devices to use the
model as-is. The physical dimension of models processed by client-device
should approach zero, as SCALing tends to zero. The value of SCALing
should also be accounted for by client-devices (in combination with
other information) to determine the appropriate distance at which the
model should be paged-in, rendered or processed. All three SCALing
factors are optional. Values of zero and negative values are not
permitted.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |3.5

| | |Range |[ 000.00001 , 999.99999 ]

| | |Length |9

| | |Default |1.0

|58 |SJID |Start Junction ID |

| | |Definition: |A unique Junction Identification Number that is used
to virtually connect the starting point of a line feature to another
point, line or polygon feature.

| | |Description: |line features stored in the same vector data file
having the same SJID or EJID are connected. line features stored in
different vector files having the same SJID or EJID as the JID listed in
the corresponding tile 2D relationship file are connected.

| | |UsageNote: |Mandatory for all features belonging to Topological
Network Datasets. Attribute is stored as a character string representing
an unsigned 64-bit number and requires conversion back into numerical
representation by client reader. This is due to the 32-bit limitation on
integer values within dBASE files (e.g., *.dbf). NOTE: In the OGC CDB
1.2 - Volume 1, "Data Type" is text numerals and "Format" is unsigned
integer64 as character string which is different from this xml. RANGE: 0
to (2^64 – 1) according to the OGC CDB 1.2 - Volume 1.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Length |20

| | |Default |None

|59 |SRD |Surface Roughness Description |

| | |Definition: |Describes the condition of the surface materials that
may be used for mobility prediction, construction material, and landing
sites.

| | |Description: |Describes the condition of the surface materials that
may be used for mobility prediction, construction material, and landing
sites.

| | |UsageNote: |Recommended for polygon features. Enumeration per Table
5-23 from the OGC CDB 1.2 - Volume 1: Surface Roughness Enumeration
Values.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !No surface roughness effect
!2 !Area of high landslide potential
!3 !Uncohesive surface material/flat
!4 !Rough
!5 !Angular
!6 !Rounded
!11 !Surface of numerous cobbles and boulders
!12 !Areas of stony terrain
!13 !Stony soil with surface rock
!14 !Stony soil with scattered boulders
!15 !Stony soil with numerous boulders
!16 !Numerous boulders
!17 !Numerous rock outcrops
!18 !Area of scattered boulders
!19 !Talus slope
!20 !Boulder Field
!31 !Highly fractured rock surface
!32 !Weathered lava flows
!33 !Unweathered lava flows
!34 !Stony soil with numerous rock outcrops
!35 !Irregular surface with deep fractures of foliation
!36 !Rugged terrain with numerous rock outcrops
!37 !Rugged bedrock surface
!38 !Sand dunes
!39 !Sand dunes/low
!40 !Sand dunes/high
!41 !Active sand dunes
!42 !Stabilized sand dunes
!43 !Highly distorted area, sharp rocky ridges
!51 !Stony soil cut by numerous gullies
!52 !Moderately dissected terrain
!53 !Moderately dissected terrain with scattered rock outcrops
!54 !Dissected floodplain
!55 !Highly dissected terrain
!56 !Area with deep erosional gullies
!57 !Steep, rugged, dissected terrain with narrow gullies
!58 !Karst areas of numerous sinkholes and solution valleys
!59 !Karst area of numerous sinkholes
!60 !Karst/hummocky terrain covered with large conical hills
!61 !Karst/hummocky terrain covered with low, broad-based mounds
!62 !Arroyo/wadi/wash
!63 !Playa/dry lake
!64 !Area of numerous meander scars and/or oxbow lakes
!65 !Solifluction lobes and frost scars
!66 !Hummocky ground, areas of frost heaving
!67 !Area of frost polygons
!68 !Area containing sabkhas
!69 !Area of numerous small lakes and ponds
!70 !Area of numerous crevasses
!81 !Area of numerous terraces
!82 !Quarries
!83 !Strip mines
!84 !Quarry/gravel pit
!85 !Quarry/sand pit
!86 !Mine tailings/waste piles
!87 !Salt evaporators
!88 !Area of numerous dikes
!89 !Area of numerous diked fields
!90 !Area of numerous fences
!91 !Area of numerous stone walls
!92 !Area of numerous man-made canals/drains/ditches
!93 !Area of numerous terraced fields
!94 !Parallel earthen mounds row crops
!95 !Area of numerous hedgerows
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|60 |SSC |Structure Shape Category |

| | |Definition: |Describes the Geometric form, appearance, or
configuration of the feature.

| | |Description: |Describes the Geometric form, appearance, or
configuration of the feature.

| | |UsageNote: |Recommended for point features, and all Network
line/polygon Figure Points features. Enumeration per Table 5-24 from the
OGC CDB 1.2 - Volume 1: Structure Shape Category Enumeration Values

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!1 !Barrel, Ton
!2 !Blimp
!3 !Boat Hull (Float)
!4 !Bullet
!5 !Reserved
!6 !Conical/Peaked/NUN
!7 !Cylindrical (Upright)/CAN
!9 !Reserved
!10 !Pillar/Spindle
!11 !Reserved
!12 !Pyramid
!13 !Reserved
!14 !Reserved
!15 !Solid/filled
!16 !Spar
!17 !Spherical (Hemispherical)
!18 !Truss
!19 !With Radome
!20 !Reserved
!21 !Artificial Mountain
!22 !Crescent
!23 !Ferris Wheel
!24 !Enclosed
!25 !Roller Coaster
!26 !Lateral
!27 !Mounds
!28 !Ripple
!29 !Star
!30 !Transverse
!31 !Reserved
!32 !Reserved
!33 !Reserved
!34 !Reserved
!36 !Windmotor
!38 !Reserved
!40 !Reserved
!46 !Open
!52 !'A' Frame
!53 !'H' Frame
!54 !'I' Frame
!56 !'Y' Frame
!57 !Reserved
!58 !Reserved
!59 !Telescoping Gasholder (Gasometer)
!60 !Mast
!61 !Tripod
!62 !Reserved
!63 !Reserved
!65 !Cylindrical with flat top
!66 !Cylindrical with domed top
!71 !Cylindrical/Peaked
!73 !Superbuoy
!74 !'T' Frame
!75 !Tetrahedron
!76 !Funnel
!77 !Arch
!78 !Multi-Arch
!79 !Round
!80 !Rectangular
!81 !Dragons Teeth
!82 !I-Beam
!83 !Square
!84 !Irregular
!85 !Diamond Shaped Buoy
!86 !Oval
!87 !Dome
!88 !Spherical with Column Support
!89 !Cylindrical or Peaked with tower support
!90 !High-Rise Building
!91 !Cylindrical
!92 !Cubic
!93 !Pole
!94 !Board
!95 !Column (Pillar)
!96 !Plaque
!97 !Statue
!98 !Cross
!107 !Tower
!108 !Scanner
!109 !Obelisk
!110 !Radome, Tower Mounted
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|61 |SSR |Structure Shape of Roof |

| | |Definition: |Describes the roof shape.

| | |UsageNote: |Recommended for point features, and all Network
line/polygon point Figures. Enumeration per Table 5-25 of the OGC CDB
1.2 - Volume 1: Structure Shape of Roof Enumeration Values.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!6 !Conical/Peaked/NUN
!38 !Curved/Round (Quonset)
!40 !Dome
!41 !Flat
!42 !Gable (Pitched)
!43 !Reserved
!44 !Reserved
!45 !Reserved
!46 !Reserved
!47 !Sawtooth
!48 !Reserved
!49 !Reserved
!50 !With Monitor
!51 !With Steeple
!55 !Flat with Monitor
!58 !Reserved
!64 !Gable with Monitor
!65 !Reserved
!66 !Reserved
!71 !Reserved
!72 !Reserved
!77 !With Cupola
!78 !With Turret
!79 !With Tower
!80 !With Minaret
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |0

|62 |TRF |Traffic Flow |

| | |Definition: |Encodes the general destination of traffic.

| | |Description: |Encodes the general destination of traffic.

| | |UsageNote: |Recommended on all Network line (except PowerLines)
features. Enumerated per DIGEST 2.1. A few examples: 3: One-way and 4:
Two-way. DEFAULT: 004 - (two-way) for RoadNetwork line features, 003 -
(one-way) for RailRoadNetwork line features. As per this issue
(https://github.com/opengeospatial/cdb-schema/issues/15) discussed in
the OGC CDB SWG, the default value changed to 004 to be unique and
machine readable.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |3

| | |Default |004

|63 |TXID |Taxiway ID |

| | |Definition: |A unique alphanumeric identifier (for the airport in
question).

| | |Description: |A unique alphanumeric identifier (for the airport in
question).

| | |UsageNote: |Recommended usage and Optional usages are per Table
5-27 from the OGC CDB 1.2 - Volume 1: Allocation of CDB Attributes to
Vector Datasets. Failure to appropriately tag airport culture with TXID
attribute will result in reduced control of taxiway-related culture by a
simulation device. NOTE: In the OGC CDB 1.2 - Volume 1, "Data Type" is
alphanumeric which is different from this xml.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Text

| | |Length |6

| | |Default |None

|64 |USP |Urban Street Pattern |

| | |Definition: |Describes the predominant geometric configuration of
streets found within the delineated area of the feature.

| | |Description: |Describes the predominant geometric configuration of
streets found within the delineated area of the feature.

| | |UsageNote: |Recommended for polygon features. Enumeration per Table
5-26 from the OGC CDB 1.2 - Volume 1: Urban Street Pattern Enumeration
Values.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Enum

| | |Enumeration a|
[cols="<,<",]
!===
!Code !Description
!0 !Unknown
!2 !Rectangular/Grid-Regular
!3 !Rectangular/Grid-Irregular
!4 !Curviline (cluster)
!6 !Concentric / Radial-Regular
!7 !Concentric / Radial-Irregular
!9 !Mixed-Curviline (cluster) and Rectangular (grid)
!10 !Mixed-Concentric / Radial and Rectangular (grid)
!11 !Mixed-Curviline (cluster) and Concentric / Radial
!12 !Reserved
!13 !line Strip
!997 !Unpopulated
!998 !Not Applicable
!999 !Other
!===

| | |Format |Integer

| | |Range |[ 0 , 999 ]

| | |Length |6

| | |Default |0

|65 |VEAI |Vendor Extended Attribute Index |

| | |Definition: |An index that points to a row entry of a
VendorExtended Attribution file for the current dataset.

| | |Description: |An index that points to a row entry of a
VendorExtended Attribution file for the current dataset. This entry
permits users to store an index to a link list set of Vendor-specific
attributes. CDB-compliant devices are not mandated to read and interpret
this field. Usage of this attribution is not portable to other
simulators because it falls outside of the documented CDB attribution
scheme. The Vendor Extended Attribution file should be located in the
same directory as the instance-level attribution file. An empty VEAI
attribute is allowed. Note that the first entry in the Vendor Extended
Attribution file has an index of 1.

| | |UsageNote: |Optional. Use when Vendor extended attribution is
required. A value of 0 indicates that there are no Vendor Extended
attributes.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Supported), Extended (Not
Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 999999 ]

| | |Length |6

| | |Default |None

|66 |WGP |Width with Greater Than 1 meter Precision |

| | |Definition: |WGP indicates the width of Network line features with
Greater Than 1 meter Precision.

| | |Description: |For line features (such as roads, railways, runways,
taxiways), WGP is a measurement of the shorter of two line axes. For a
bridge, the width is the measurement perpendicular to the axis between
the abutments. For powerlines, the width is the distance between the
outermost wires.

| | |UsageNote: |Recommended on all Network line (except PowerLines)
features. When supplied for coastline, WGP corresponds to average width
of coastline due to water height variations (such as tides) and wave
action.

| | |Compatibility: |OGC CDB 1.0, DIGEST 2.1

| | |Level |Instance (Preferred), Class (Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Floating-Point

| | |Precision |5.3

| | |Range |[ 0.000 , 99999.999 ]

| | |Length |9

| | |Default |None

| | |Unit |1

|67 |DAMA |Damage Level |

| | |Definition: |Represents the level of damage of the feature and its
model, if applicable.

| | |Description: |The level is expressed as a percentage where a value
of 0 means no damage at all and a value of 100 means fully damaged and
completely destroyed. In the case of network datasets, the level of
damage should be interpreted as a measure of the incapacity of the
feature to perform its function. For instance, a road network whose
damage level is 75% tells the client that it is only able to perform 25%
of its intended function. As a result, a certain client may decide that
it cannot use the road network while another client may continue to do
so.

| | |UsageNote: |In the context of HLA/DIS, the concept of DAMA maps
directly to the concepts of Damage State for which the standards define
4 states named No Damage, Slight Damage, Moderate Damage, and Destroyed.
The CDB standard suggests the following mapping between CDB DAMA and
HLA/DIS states. From CDB to HLA/DIS, if DAMA < 25 then State = No
Damage; else if DAMA < 50 then State = Slight Damage; else if DAMA < 75
then State = Moderate Damage; else State = Destroyed. From HLA/DIS to
CDB, if State = Destroyed then DAMA = 100; else if State = Moderate
Damage then DAMA = 66; else if State = Slight Damage then DAMA = 33;
else DAMA = 0.

| | |Compatibility: |OGC CDB 1.0

| | |Level |Instance (Preferred), Class (Not Supported), Extended
(Supported),

| | |Type |Numeric

| | |Format |Integer

| | |Range |[ 0 , 100 ]

| | |Length |3

| | |Default |0

| | |Unit |7
|===

'''''

=== Units

[cols="<,<,<,<",]
|===
|Code |Symbol |Name |Description
|1 |m |meter |To measure a length.
|2 |deg |degree |To mesure an angle.
|3 |rad |radian |To mesure an angle.
|4 |kph |Kilometer per hour |To measure a speed.
|5 |g |gram |To measure a mass.
|6 |s |second |To measure time.
|7 |% |Percentage |A value between 0 and 100.
|===

'''''

=== Scalers

[cols="<,<,<,<,<",]
|===
|Code |Symbol |Mutiplier |Name |Description
|1 |k |1000 |kilo |A multiplier: thousand
|2 |m |0.001 |milli |A divisor: thousandth
|===
