[[Conventions]]
== Conventions

This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

[[Identifiers]]
=== Identifiers

The normative provisions in this standard are denoted by the URI namespace

    http://www.opengis.net/spec/cdb/1.0/core

All requirements that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “req” in a requirement URI denotes:

      http://www.opengis.net/spec/cdb/1.0/core/req

An example might be:

req/core/platform

All conformance tests that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “conf” in a requirement URI denotes:

        http://www.opengis.net/spec/cdb/1.0/core/conf

[[CDBXMLSchemaDefinitions]]
=== CDB XML Schema Definitions

NOTE: The content in this clause was originally in CDB Volume 2, Annex J.

The CDB standard makes an extensive use of XML to describe several parts of the standard. XML is used to describe CDB metadata, controlled vocabularies, to store global datasets, to add attributes and information to 3d models, such as an OpenFlight model, to describe base and composite materials, and so forth.

The following XML Schemas can be found in the `\CDB\Metadata\Schema` subdirectory of the CDB Standard Distribution Package:

* BaseMaterialTable.xsd
* CompositeMaterialTable.xsd
* Configuration.xsd
* Defaults.xsd
* FeatureDataDictionary.xsd
* Lights.xsd
* LightsTuning.xsd
* ModelComponents.xsd
* ModelMetadata.xsd
* OpenFlightModelExtensions.xsd
* VectorAttributes.xsd
* Version.xsd

Clause 1.4.3 and 1.4.4 provides more information on these files.

[[TheCDBNamespace]]
==== The CDB Namespace

The CDB standard makes use of several XML namespaces to isolate the definitions of its schemas. The name of these namespaces is built around a base URL.

[[SchemaConventions]]
==== Schema Conventions

The target namespace of all CDB schemas follow this pattern:

"http://schemas.opengis.net/cdb/`Version`/`Name`"

Where the Name is identical to the filename portion of the file containing the schema and Version is the version number of the schema.

To illustrate how a target namespace is composed, here is the target namespace of the schema found in Version.xsd (item 12 in the list above):

"http://schemas.opengis.net/cdb/1.2/Version"

IMPORTANT NOTE: For brevity, the literal “CDB” in a schema path should be expanded to:

http://schemas.opengis.net/cdb/1.2/`Name`

in any implementation.

[[CDBMetadata,ControlledVocabulary,andMetadataFiles]]
=== CDB Metadata, Controlled Vocabulary, and Metadata Files

There are a number of CDB XML files that are stored and referenced from the CDB metadata folder. First, some terms are defined

[[Metadata]]
==== Metadata

http://www.merriam-webster.com/dictionary/metadata[Metadata] is data that provides information about other data. In the geospatial community and the rapidly emerging spatial web community, metadata is critical to operations such as discovery and determining whether a resource is “fit for purpose”. Three distinct types of metadata exist: *descriptive metadata*, *structural metadata*, and **administrative metadata** (https://www.niso.org/[National Information Standards Organization (NISO)]).

* Descriptive metadata describes a resource for purposes such as discovery and identification. It can include elements such as title, abstract, author, and keywords.
* Structural metadata is metadata about containers of metadata and indicates how compound objects are put together, for example, how pages are ordered to form chapters.
* Administrative metadata provides information to help manage a resource, such as when and how it was created, file type and other technical information, and who can access it. <end Wikipedia>

The geospatial community has a long and extensive history in defining and using metadata for geospatial resources. Without metadata, discovery of required resources and determination of whether a resource is “Fit for Purpose” becomes difficult if not impossible. The geospatial community makes use of all three types of metadata, although the first and third are more critical. The CDB use of metadata focuses on use cases 1 and 3.

1.  Controlled Vocabulary
+
https://en.wikipedia.org/wiki/Controlled_vocabulary[Controlled vocabularies] provide a way to organize knowledge for subsequent retrieval and use. They are used in subject indexing schemes, subject headings, thesauri, taxonomies and other forms of knowledge organization systems. Controlled vocabulary schemes mandate the use of predefined, authorized terms that have been preselected by the designers of the schemes, in contrast to natural language vocabularies, which have no such restriction. The use of controlled vocabularies in standards such as CDB can significantly increase interoperability and consistent understanding of the semantics. Controlled vocabularies typically are managed through formal processes and official governance.
2.  Enumerations
+
In computer programming, an enumerated type (also called an enumeration) is a data type consisting of a set of named values called elements, members, or enumerators of the type. The enumerator names are usually identifiers that behave as constants in the language. Similarly, in a database enumerated (enum) types are data types that comprise a static, ordered set of values. They are equivalent to the enum types supported in a number of programming languages. An example of an enum type might be the days of the week, or a set of status values for a piece of data.

[[CDBmetadata,controlledvocabularies,andenumerationssummarytable]]

==== CDB metadata, controlled vocabularies, and enumerations summary table

The following is a list of these files. While the general term being used is “metadata” in terms of the file system structure, a number of these files are either controlled vocabularies or attribute files. Please read link:#cdb-structure[Clauses 1.4.4, 1.5, and 3.1.1 Metadata Directory] for more detailed information on the files maintained in that folder. The following table identifies the files stored in the metadata folder and whether they are metadata or controlled vocabularies.

|===
|Name|Location|Type|Extension|M/O

|CDB_Attributes|\CDB\Metadata|CV|.xml|O
|Configuration|\CDB\Metadata|M|.xml|O
|Datasets|\CDB\Metadata|CV|.xml|O
|Lights|\CDB\Metadata|CV|.xml|O
|Lights___xxx__|\CDB\Metadata|CV|.xml|C
|Defaults|\CDB\Metadata|E|.xml|O
|Materials|\CDB\Metadata|CV|.xml|O
|Modelcomponents|\CDB\Metadata|CV|.xml|O
|MovingModelCodes|\CDB\Metadata|E|.xml|O
|Version|\CDB\Metadata|M|.xml|M
|FeatureDataDictionary|\CDB\Metadata|CV|.xml|O
|DISCountryCodes|\CDB\Metadata|E|.xml|O
|Globalgeometadata|\CDB\Metadata|M|.<ext>|O
|Localgeometadata|Determined by directory path rules|M|.<ext>|O
|===

NOTE: Type:  CV = Controlled Vocabulary, M = Metadata, E = Enumeration

NOTE: M/O: [M = Mandatory, O = Optional, C = Conditional]

NOTE: <ext> could be xml for XML, jsn for JSON, and other extensions based on the encoding technology used for the geospatial metadata

Each of these files is described in detail later in this document.

In CDB version 1.1 and later, additional metadata requirements and elements are specified. These are traditional metadata including geospatial metadata. Specifically, the reader should reference clauses 3.1.1, 3.1.2, and 5.1 (special focus on 5.1.6). Also, make special note of the guidance in clause “3.2.3.2 How to handle the metadata directory.”

[[CDBDirectoryFileNamingandStructure]]
=== CDB Directory File Naming and Structure

The CDB directory and folder structure is defined by a combination of folder hierarchy and metadata files delivered with the CDB Standard Distribution Package.

The /CDB folder hierarchy provides a complete list of directory and filename patterns of the CDB; it summarizes the structure of the CDB presented in chapter 3 of this document. The following files contain enumerations and controlled vocabularies that are necessary to expand the patterns:

* /CDB/Metadata/FeatureDataDictionary.xml provides the list of directory names associated with feature codes.
* /CDB/Metadata/MovingModelCodes.xml provides the list of names for DIS Entity Kinds, Domains, and Categories.
* /CDB/Metadata/DISCountryCodes.xml contains the list of DIS Country Names.

Together, these files provide all the information required to build the names of all directories permitted by the standard.

The following file extensions are used:

[options="autowidth"]
|===
|File Format|Minimal Version Number|Extension

|TIFF|6.0|*.tif
|SGI Image|1.0|*.rgb
|JPEG 2000|1.0|*.jp2
|OpenFlight|16.0|*.flt
|Shapefile|Esri White Paper, July 98|*.shp, *.shx
|dBASE|III+|*.dbf, *.dbt
|XML|1.0 and later|*.xml, *.xsd
|ZIP|6.3.1 and later|*.zip
|GeoPackage|1.1 and later|*.gpkg
|===

Previous version sf the above table had a column labeled: _CDB Client-device Behavior for Prior Versions"_. All rows had the label _Ignores data_. The column has been removed but the value is still valid.
