[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

//*A.1 Conformance Test Class: OGC CDB Core Standard*
=== Conformance Test Class: OGC CDB Core Standard

This section describes conformance test for the OGC CDB Core Standard. These abstract test cases describe the conformance criteria for verifying the structure and content of any data store or database claiming conformance to the CDB 1.2 standard.

The conformance class base id is “http://www.opengis.net/spec/http://opengis.net/spec/CDB/1.2/” and all of the other conformance tests URLs are created in this path. Each conformace class then appends: "core/conf/" to this base ID. Another issue that the reader should pay attention to is the test method. When the test method is assigned with “Visual”, it means that the purpose of the test should be “visually” investigate the file contents, image, or other content.

//**A.1.1 General CDB Data Store and Implementation**
==== General CDB Data Store and Implementation

The following conformance class is designed to determine if a CDB implementation include all elements of the CDB Core Data Model as defined in Annex A.

include::abstract_tests/TEST001.adoc[]

//**A.1.2 Platform**
==== Platform

The following conformance class is designed to determine if the target hardware system (laptop, desktop, etc) has the resources necessary to store, manage, update, and access a CDB data store.

include::abstract_tests/TEST005.adoc[]

//**A.1.3 General Data Representation **
==== General Data Representation

The following conformance class is designed to determine if the general data representation requirements are met.

include::abstract_tests/TEST006.adoc[]

//**A.1.4 Structure-Tiling Model**
==== Structure-Tiling Model

The following conformance class is designed to determine if the CDB structure model has the necessary requirements.

include::abstract_tests/TEST011.adoc[]


//**A.1.5 Light Naming**
==== Light Naming

The following conformance class is designed to determine if any modeled light point is described based on the comprehensive set of light hierarchies suited to the needs of visual simulation.

include::abstract_tests/TEST017.adoc[]

//**A.1.6 Light Name Hierarchy**
==== Light Name Hierarchy

The following conformance class is designed to determine if a light type is added to the hierarchy of light names has the necessary requirements.

include::abstract_tests/TEST018.adoc[]

//**A.1.7 Materials**
==== Materials

The following conformance class is designed to deal with the handling of materials that make up the synthetic environment when adding a new model component.

include::abstract_tests/TEST022.adoc[]

//**A.1.8 CDB Root Directory**
==== CDB Root Directory

The following conformance class is designed to deal with the handling of top-level directory structure of the CDB from the root directory.


include::abstract_tests/TEST029.adoc[]

//**A.1.9 Version Metadata File**
==== A.1.9 Version Metadata File

The following conformance class is designed to determine if Version.xml has the necessary requirements.

include::abstract_tests/TEST033.adoc[]

//**A.1.10 FLIR Metadata File**
==== FLIR Metadata File

The following conformance class is designed to determine if Lights_FLIR.xml have the necessary requirements.


include::abstract_tests/TEST034.adoc[]


//**A.1.11 Data Store Version Directory Structure**
==== Data Store Version Directory Structure

The following conformance class is designed to deal with the handling files and the directory structure of CDB Versions.

include::abstract_tests/TEST035.adoc[]

//**A.1.12 Model Types**
==== Model Types

The following conformance class is designed to determine if cultural features of a CDB database have the necessary requirements.

include::abstract_tests/TEST039.adoc[]

//**A.1.13 Geospecific Model (GSModel) Storage**
==== Geospecific Model (GSModel) Storage

The following conformance class is designed to determine if GSModels have the necessary requirements.

include::abstract_tests/TEST040.adoc[]


//*A.1.14b Geotypical Models LOD Resolution*
*Geotypical Models LOD Resolution*

NOTE: Labelled as A.1.14b Geotypical Models LOD Resolution in the MS Word version of the standard

include::abstract_tests/TEST041.adoc[]


//**A.1.14 Geotypical Models (GTModel) Naming Conventions**
==== Geotypical Models (GTModel) Naming Conventions

The following conformance class is designed to determine if the GTModels have the necessary requirements.

include::abstract_tests/TEST042.adoc[]

//**A.1.15 Moving Model (MModel) Naming Conventions**
==== Moving Model (MModel) Naming Conventions

The following conformance class is designed to determine if MModel library datasets have the necessary requirements.

include::abstract_tests/TEST057.adoc[]

//**A.1.16 Tiled Datasets**
==== Tiled Datasets

The following conformance class is designed to determine if the tile dataset have the necessary requirements.

include::abstract_tests/TEST064.adoc[]


//**A.1.17 Archive Names**
==== Archive Names

The following conformance class is designed to determine if the archive names have the necessary requirements.

include::abstract_tests/TEST068.adoc[]


//**A.1.18 NavData Naming Convention**
==== NavData Naming Convention

The following conformance class is designed to determine if each field of the NavData file name is correctly selected based on the table 3-32.

include::abstract_tests/TEST073.adoc[]


//**A.1.19 Metadata Datasets**
==== Metadata Datasets

The following conformance class is designed to determine if all the metadata files are located in the correct folder.

include::abstract_tests/TEST074.adoc[]


//**A.1.20 Navigation Data**
==== Navigation Data

The following conformance class is designed to determine if all the NavData dataset represents are correctly located in the folder and have correct materials. NavData supports several simulation subsystems such as the Instrument Landing System (ILS), Inertial Navigation/Global Positioning System, and Microwave Landing System Communications.

include::abstract_tests/TEST081.adoc[]


//**A.1.21 Tiled Raster Datasets**
==== Tiled Raster Datasets

The following conformance class is designed to determine if all the all of the CDB raster datasets have correct grid sampling and structure.


include::abstract_tests/TEST085.adoc[]


//**A.1.22 Tiled Elevation Dataset**
==== Tiled Elevation Dataset

The following conformance class is designed to determine if the CDB terrain elevation data elements have the necessary requirements.

include::abstract_tests/TEST088.adoc[]


//A.1.23 Tiled Terrain Bathymetry**
==== Tiled Terrain Bathymetry

The following conformance class is designed to determine if the bathymetry component consists of all the necessary formats and specifications.

include::abstract_tests/TEST096.adoc[]


//**A.1.24 Tiled JPEG Metadata**
==== Tiled JPEG Metadata

The following conformance class is designed to determine if the JPEG 2000 files has all the necessary formats and specifications.

include::abstract_tests/TEST099.adoc[]

//**A.1.25 Visible Spectrum Terrain Imagery (VSTI)**
==== Visible Spectrum Terrain Imagery (VSTI)

The following conformance class is designed to determine if the VSTI dataset implicitly follows the grid element conventions and specifications.

include::abstract_tests/TEST101.adoc[]


//**A.1.26 Visible Spectrum Terrain Light Map (VSTLM)**
==== Visible Spectrum Terrain Light Map (VSTLM)

The following conformance class is designed to determine if the VSTI dataset implicitly follows the grid element conventions and specifications.

include::abstract_tests/TEST103.adoc[]


//**A.1.27 Raster Composite Material**
==== Raster Composite Material

The following conformance class is designed to determine if the raster composite material dataset which consist of several (up to 255) composite materials for each pixel follows the necessary conventions and specifications.

include::abstract_tests/TEST104.adoc[]


//**A.1.28 Tiled Vector Datasets**
==== Tiled Vector Datasets

The following conformance class is designed to determine if the tiled vector datasets follows the necessary specifications.

include::abstract_tests/TEST107.adoc[]

//**A.1.29 Vector Datasets Mandatory Attribute Usage**
==== Vector Datasets Mandatory Attribute Usage

The following conformance class is designed to determine if the vector datasets attribute follows the necessary specifications.

include::abstract_tests/TEST113.adoc[]


//**A.1.30 Vector Datasets Topology**
==== Vector Datasets Topology

The following conformance class is designed to determine if the vector dataset topology follows the necessary specifications.

include::abstract_tests/TEST117.adoc[]


//**A.1.31 Elevation Constraints**
==== Elevation Constraints

The following conformance class is designed to determine if the modeler edits and regenerate the elevation datasets based on the elevation constraints and their specifications.

include::abstract_tests/TEST121.adoc[]

//**A.1.32 Tiled Road Networks**
==== Tiled Road Networks

The following conformance class is designed to determine if the RoadNetwork Dataset is used to specify tiled road networks.

include::abstract_tests/TEST124.adoc[]


//**A.1.33 Tiled Railroad Networks**
==== Tiled Railroad Networks

The following conformance class is designed to determine if the RailRoadNetwork Dataset is used to specify tiled railroad networks.

include::abstract_tests/TEST125.adoc[]


//**A.1.34 Tiled PowerLine Networks**
==== Tiled PowerLine Networks

The following conformance class is designed to determine if the PowerLineNetwork Dataset is used to specify tiled powerline networks.

include::abstract_tests/TEST126.adoc[]


//**A.1.35 Tiled Hydrography Networks **
==== Tiled Hydrography Networks

The following conformance class is designed to determine if the HydrographyNetwork Dataset is used to specify tiled hydrography networks.

include::abstract_tests/TEST127.adoc[]


//**A.1.36 Vector Composite Material Table (VCMT)**
==== Vector Composite Material Table (VCMT)

The following conformance class is designed to determine if the CDB geocells have at least one VCMT.xml file with the required list of attributes for the composite materials of vector datasets.

include::abstract_tests/TEST128.adoc[]


//**A.1.37 GeoSpecific Model Descriptor**
==== GeoSpecific Model Descriptor

The following conformance class is designed to determine if the CDB geocells have one GeoSpecific Model Descriptor placed at the correct LOD for each GeoSpecific Model's level of detail.

include::abstract_tests/TEST129.adoc[]
